default_config:

logger:
  default: info
  logs:
    custom_components.oebb: debug

debugpy:

sensor:
  - platform: oebb
    stops: '4429'
    firstnext: first
  - platform: oebb
    stops: '4429'
    firstnext: next
  - platform: oebb
    firstnext: first
    stops:
      - '4429'
      - '3230'
